### ISSUE TITLE
Implement throughput measurement function

### ISSUE THREAD

**Issue by aobolensk** [embedded-dev-research/itlab_2023#11]

**Comment by allnes** [comment]
Article about common metrics - https://younsess-elbrag.medium.com/measuring-neural-network-performance-latency-and-throughput-on-gpu-5d54657871f0

**Comment by allnes** [comment]
More information - https://towardsdatascience.com/the-correct-way-to-measure-inference-time-of-deep-neural-networks-304a54e5187f

**Comment by allnes** [comment]
https://mse238blog.stanford.edu/2018/07/puyang/how-to-measure-deep-learning-performance/
