### ISSUE TITLE
Implement graph data structure

### ISSUE THREAD

**Issue by aobolensk** [embedded-dev-research/itlab_2023#3]
Node structure:
- function description

**Comment by AndreySorokin7** [comment]
Появился маленький вопрос. На данный момент у меня готовая общая структура графа. Последнюю свою вариацию я запушил в свою ветку. Мне стоит дальше углубляться и добавлять более точные данные внутрь узлов или на данный момент этого хватит? Просто на сколько я понял внутри узлов для каждого вида должна содержаться некоторая активная часть закладываемая уже другим человеком. А в классе дерево необходимо будет устроить некоторую функцию обхода которую будет сложновато на данном этапе представить. Нужно ли сейчас делать Pull requests или всё таки необходимо добавить ещё больше функционала? И ещё маленький вопросик по поводу моего большого количества commit. Не страшно ли это и вдруг это кому то мешает? Можно ли так дальше делать?

**Comment by aobolensk** [comment]
На данный момент уже можно делать pull request, детали реализации конкретных слоев будем постепенно добавлять в следующих патчах. Большое количество коммитов не помешает, при слиянии в основную ветку они превратятся в один, а в pull request'е останется все, как и раньше
