### ISSUE TITLE
timer.is_elapsed_time_returns_nearly_correct_time test failed sporadically on macOS

### ISSUE THREAD

**Issue by aobolensk** [embedded-dev-research/itlab_2023#30]
```
[ RUN      ] timer.is_elapsed_time_returns_nearly_correct_time
/Users/runner/work/itlab_2023/itlab_2023/test/test.cpp:63: Failure
Expected: (res_time) <= (350), actual: 357.29798399999999 vs 350

[  FAILED  ] timer.is_elapsed_time_returns_nearly_correct_time (357 ms)
```
Log example: https://github.com/embedded-dev-research/itlab_2023/actions/runs/7158701945/job/19491090349?pr=29

**Comment by NeiroYT** [comment]
I can change accuracy to +-200 ms instead of +-100 ms, maybe 1/5 of second is not a big deal

**Comment by aobolensk** [comment]
Increasing gap is ok for me, but as for `+-` I'm not sure, because it should be not less according to function specification.

**Comment by NeiroYT** [comment]
Then i'll remove upper bound, if any lag or freeze can break it.

**Comment by aobolensk** [comment]
Ok
