### ISSUE TITLE
AlexNet arch review

### ISSUE THREAD

**Issue by aobolensk** [embedded-dev-research/itlab_2023#4]
https://arxiv.org/pdf/1602.07360.pdf

- network graph structure
- what layers are needed to implement
- visualize using https://netron.app/

**Comment by allnes** [comment]
Articles about AlexNet in russian:
- https://neurohive.io/ru/vidy-nejrosetej/alexnet-svjortochnaja-nejronnaja-set-dlja-raspoznavanija-izobrazhenij/
- https://habr.com/ru/companies/nix/articles/430524/
- https://www.reg.ru/blog/stehnfordskij-kurs-lekciya-9-arhitektury-cnn/

**Comment by suvorovDm-1** [comment]
AlexNet - одна из самых сильных сверточных нейронных сетей в сфере распознавания изображения.
Эта нейронная сеть построена на основе сети LeNet, но является более современной и улучшенной сетью.

**Comment by suvorovDm-1** [comment]
Принцип работы:
1) Изначально на вход подаётся фотография размером 227×227×3
2) На сверточных слоях к изображению применяются фильтры с различными характеристиками: размер, шаг, отступ.
Фильтры - это свертки. Это специальные вектора весов, которые упорядочены в трехмерный "куб" с двумя параметрами -  ширины, высоты и третьим измерением, который равен трём - это три слоя цвета изображения (красного, синего, зеленого).
Этот вектор весов скалярно умножается на область картинки, которая выбирается условно с левого верхнего угла. Следующая область для применения фильтра располагается с некоторым шагом от предыдущей.
Наглядно представлена работа фильтров по следующим ссылкам:
https://pythonpip.ru/pytorch/svertochnaya-neyronnaya-set?ysclid=lpvadvz5kx278550434
https://proglib.io/p/convolution?ysclid=lpvaayt426963818457

Также существует следующая проблема: если фильтрами не "заходить" за границы картинки, то значения граничных пикселей картинки будут подвержены обработке фильтрами меньшее количество раз, чем центральные пиксели. Для решения этой проблед подаётся фотография размером 227×227×3
2) На сверточных слоях к изображению применяются фильтры с различными характеристиками: размер, шаг, отступ.
Фильтры - это свертки. Это специальные вектора весов, которые упорядочены в трехмерный "куб" с двумя параметрами -  ширины, высоты и третьим измерением, который равен трём - это три слоя цвета изображения (красного, синего, зеленого).
Этот вектор весов скалярно умножается на область картинки, которая выбирается условно с левого верхнего угла. Следующая область для применения фильтра располагается с некоторым шагом от предыдущей.
Наглядно представлена работа фильтров по следующим ссылкам:
https://pythonpip.ru/pytorch/svertochnaya-neyronnaya-set?ysclid=lpvadvz5kx278550434
https://proglib.io/p/convolution?ysclid=lpvaayt426963818457

Также существует следующая проблема: если фильтрами не "заходить" за границы картинки, то значения граничных пикселей картинки будут подвержены обработке фильтрами меньшее количество раз, чем центральные пиксели. Для решения этой проблемы к границам картинки добавляются фиктивные значения, например 0.
Этот процесс также описан по указанным выше ссылкам

После применения скалярного фильтром ко всем доступным областям картинки из результатов будет сформирован куб размером: мы к границам картинки добавляются фиктивные значения, например 0.
Этот процесс также описан по указанным выше ссылкам

После применения скалярного фильтром ко всем доступным областям картинки из результатов будет сформирован куб размером (если не применяется отступ): ( (H0 - h_m) / s + 1 ) x ( (W0 - w_m) / s + 1 ) x 3
где H0 и W0 - высота и ширина картинки, поданной на вход сверточному слою
h_m и w_m - высота и ширина фильтра
s - шаг фильтра

Краткая схема:
[227×227×3] INPUT
[55×55×96] CONV1: 96 фильтров 11×11с шагом 4, отступ 0
[27×27×96] MAX POOL1: фильтры 3×3 с шагом 2
[27×27×96] NORM1: слой нормализации
[27×27×256] CONV2: 256 фильтров 5×5 с шагом 1, отступ 2
[13×13×256] MAX POOL2: фильтры 3×3 с шагом 2
[13×13×256] NORM2: слой нормализации
[13×13×384] CONV3: 384 фильтра 3×3 с шагом 1, отступ 1
[13×13×384] CONV4: 384 фильтра 3×3 с шагом, отступ 1
[13×13×256] CONV5: 256 фильтров 3×3 с шагом 1, отступ 1
[6×6×256] MAX POOL3: фильтры 3×3 с шагом 2
[4096] FC6: 4096 нейронов
[4096] FC7: 4096 нейронов
[1000] FC8: 1000 нейронов (метки класса)
-- | --


</div>
</body>
</html>

**Comment by suvorovDm-1** [comment]
![AlexNet](https://github.com/embedded-dev-research/itlab_2023/assets/113026535/6866f3d8-e0f8-4491-b430-2e926d7b2380)

**Comment by suvorovDm-1** [comment]
На изображении некоторые числовые параметры могут отличаться от описанных выше мной.
Но концептуально это не влияет на устройство графа связей нейронной сети.

**Comment by aobolensk** [comment]
@suvorovDm-1 Have you tried to visualize using https://netron.app/ ?

**Comment by suvorovDm-1** [comment]
visual model of AlexNET on OpenVino:
![alexnet xml](https://github.com/embedded-dev-research/itlab_2023/assets/113026535/2d87902f-8c07-42c1-af45-2c5a029c8936)

**Comment by NeiroYT** [comment]
ONNX Face detection model
![version-RFB-320](https://github.com/embedded-dev-research/itlab_2023/assets/119765880/dc993b70-40a2-46e6-969e-387fce9ca560)

**Comment by AndreySorokin7** [comment]
Caffe
![tE88FWVThW4](https://github.com/embedded-dev-research/itlab_2023/assets/129724280/21f45609-74fc-4ed1-ab2d-bec0701eb9d7)

**Comment by Semyon1104** [comment]
TensorFlow
![saved_model pb](https://github.com/embedded-dev-research/itlab_2023/assets/129722895/adcebca5-d089-46c0-a21f-639be1209113)

**Comment by Semyon1104** [comment]
TensorFlow
![Uploading tensorflowjs_model.pb.png…]()

**Comment by Semyon1104** [comment]
TensorFlow
![tensorflowjs_model pb](https://github.com/embedded-dev-research/itlab_2023/assets/129722895/34e7b49e-2df5-415e-b650-7fea6d729c62)
