### ISSUE TITLE
CMake GLOB_RECURSE problem

### ISSUE THREAD

**Issue by NeiroYT** [embedded-dev-research/itlab_2023#51]
After #50 all libraries are glued together now due to file(GLOG_RECURSE ...) three times
Now graph_headers, layers_headers, perf_headers are the same
![image](https://github.com/embedded-dev-research/itlab_2023/assets/119765880/432edb7e-fa44-424e-b5d0-c93c3a5501f3)
![image](https://github.com/embedded-dev-research/itlab_2023/assets/119765880/7e28b665-2fa4-4133-9115-2149f6816473)
@aobolensk

**Comment by NeiroYT** [comment]
Something like this will fix this
```cmake
file(GLOB_RECURSE graph_headers graph/*.h graph/*.hpp)
set(GRAPH_HEADERS "${graph_headers}" PARENT_SCOPE)

file(GLOB_RECURSE layers_headers layers/*.h layers/*.hpp)
set(LAYERS_HEADERS "${layers_headers}" PARENT_SCOPE)

file(GLOB_RECURSE perf_headers perf/*.h perf/*.hpp)
set(PERF_HEADERS "${perf_headers}" PARENT_SCOPE)
```

**Comment by aobolensk** [comment]
I agree, this fix is valid. Feel free to submit a PR
