### ISSUE TITLE
Implement PNG format reader using OpenCV

### ISSUE THREAD

**Issue by aobolensk** [embedded-dev-research/itlab_2023#8]

**Comment by Semyon1104** [comment]
Есть вопрос по заданию - Вы сказали в пятницу, что пользователь сам скачает библиотеку. Он должен будет скачивать openCV вместе с нашим проектом и работать с ним через git submodule --init --recursive для дальнейшей установки? Или openCV больше не нужен нам как сабмодуль и в инструкции указывать сразу оригинальный репозиторий или готовые файлы для скачивания?

**Comment by Semyon1104** [comment]
И возможно ли в инструкции по установке на Windows указывать работу только с Visual Studio и не рассматривать другие среды разработки?

**Comment by aobolensk** [comment]
Да, можно

**Comment by Semyon1104** [comment]
А можно еще узнать по поводу вопроса выше?

**Comment by aobolensk** [comment]
> Есть вопрос по заданию - Вы сказали в пятницу, что пользователь сам скачает библиотеку. Он должен будет скачивать openCV вместе с нашим проектом и работать с ним через git submodule --init --recursive для дальнейшей установки? Или openCV больше не нужен нам как сабмодуль и в инструкции указывать сразу оригинальный репозиторий или готовые файлы для скачивания?

Можно указать инструкции для скачивания без использования сабмодулей, просто со скачиванием бинарных файлов через apt/pip/с официального сайта/c github

**Comment by Semyon1104** [comment]
Все понял, спасибо

**Comment by Semyon1104** [comment]
Нам нужен будет openCV еще для чего-то кроме чтения изображений? Если нет, то я думаю проще добавить в 3rdparty готовые файлы openCV и тогда будет намного проще все собрать
